import { useEffect, useState } from "react";
import axios from "axios";
import toast from "react-hot-toast";

function AdminReviews() {
  const [reviews, setReviews] = useState([]); const [loading, setLoading] = useState(true); const token = localStorage.getItem("token");
  const loadReviews = async () => { try { const { data } = await axios.get("https://furniselect-ai.onrender.com/api/admin/reviews", { headers: { Authorization: `Bearer ${token}` } }); setReviews(data); } catch (error) { toast.error(error.response?.data?.message || "Could not load reviews"); } finally { setLoading(false); } };
  useEffect(() => { loadReviews(); }, []);
  const removeReview = async (review) => { if (!window.confirm("Remove this review from the product?")) return; try { await axios.delete(`https://furniselect-ai.onrender.com/api/admin/reviews/${review.productId}/${review._id}`, { headers: { Authorization: `Bearer ${token}` } }); setReviews((current) => current.filter((item) => item._id !== review._id)); toast.success("Review removed"); } catch (error) { toast.error(error.response?.data?.message || "Could not remove review"); } };
  return <main className="admin-theme min-h-screen bg-[#f7f3ee] px-5 py-10 lg:px-8"><div className="mx-auto max-w-[1320px]"><div className="border-b border-[#e5d9cf] pb-8"><p className="eyebrow">Customer voice</p><h1 className="mt-3 text-5xl">Reviews</h1><p className="mt-3 text-[#756b63]">Keep product feedback helpful, honest and on-brand.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="soft-card rounded-2xl p-5"><p className="text-sm text-[#897e75]">Published reviews</p><p className="mt-2 text-3xl font-bold">{reviews.length}</p></div><div className="soft-card rounded-2xl p-5"><p className="text-sm text-[#897e75]">Average rating</p><p className="mt-2 text-3xl font-bold">{reviews.length ? (reviews.reduce((sum, review) => sum + review.rating, 0) / reviews.length).toFixed(1) : "—"} <span className="text-lg text-[#b9794d]">★</span></p></div><div className="soft-card rounded-2xl p-5"><p className="text-sm text-[#897e75]">Moderation</p><p className="mt-2 text-3xl font-bold text-[#4d8b62]">Active</p></div></div><div className="mt-8 grid gap-5 lg:grid-cols-2">{loading ? <div className="rounded-2xl bg-white p-10 text-center text-[#897e75]">Loading reviews...</div> : reviews.length === 0 ? <div className="rounded-2xl bg-white p-14 text-center text-[#897e75]">No customer reviews yet.</div> : reviews.map((review) => <article key={review._id} className="rounded-2xl border border-[#e5d9cf] bg-white p-6 shadow-[0_14px_38px_rgba(73,48,32,.05)]"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.14em] text-[#9a6038]">{review.productTitle}</p><h2 className="mt-2 text-xl font-semibold">{review.name}</h2><p className="mt-1 text-sm text-[#897e75]">{review.email || "Verified customer"}</p></div><div className="text-right"><p className="text-lg tracking-widest text-[#b9794d]">{"★".repeat(Math.max(0, Math.min(5, review.rating)))}</p><p className="mt-1 text-xs text-[#897e75]">{review.createdAt ? new Date(review.createdAt).toLocaleDateString() : ""}</p></div></div><p className="mt-5 leading-7 text-[#594e47]">“{review.comment}”</p><button onClick={() => removeReview(review)} className="mt-5 rounded-lg border border-[#e5b8ae] px-3 py-2 text-xs font-semibold text-[#a04739] transition hover:bg-[#fff5f3]">Remove review</button></article>)}</div></div></main>;
}
export default AdminReviews;
