import { useEffect, useState } from "react";
import axios from "axios";
import toast from "react-hot-toast";

const defaults = { storeName: "FurniSelect", supportEmail: "support@furniselect.com", supportPhone: "+91 7651971774", announcement: "Thoughtful furniture for modern living.", lowStockThreshold: 5 };

function AdminSettings() {
  const [form, setForm] = useState(defaults); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const token = localStorage.getItem("token");
  useEffect(() => { axios.get("https://furniselect-ai.onrender.com/api/admin/settings", { headers: { Authorization: `Bearer ${token}` } }).then(({ data }) => setForm({ ...defaults, ...data })).catch((error) => toast.error(error.response?.data?.message || "Could not load settings")).finally(() => setLoading(false)); }, []);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const save = async (event) => { event.preventDefault(); setSaving(true); try { const { data } = await axios.patch("https://furniselect-ai.onrender.com/api/admin/settings", form, { headers: { Authorization: `Bearer ${token}` } }); setForm({ ...defaults, ...data }); toast.success("Settings saved"); } catch (error) { toast.error(error.response?.data?.message || "Could not save settings"); } finally { setSaving(false); } };
  const fields = [{ key: "storeName", label: "Store name", hint: "Shown across your store experience." }, { key: "supportEmail", label: "Support email", hint: "Where customer questions should go." }, { key: "supportPhone", label: "Support phone", hint: "Displayed in customer support areas." }];
  return <main className="admin-theme min-h-screen bg-[#f7f3ee] px-5 py-10 lg:px-8"><div className="mx-auto max-w-[980px]"><div className="border-b border-[#e5d9cf] pb-8"><p className="eyebrow">Store control</p><h1 className="mt-3 text-5xl">Settings</h1><p className="mt-3 text-[#756b63]">Keep your storefront details and inventory rules up to date.</p></div>{loading ? <div className="mt-8 rounded-2xl bg-white p-12 text-center text-[#897e75]">Loading settings...</div> : <form onSubmit={save} className="mt-8 space-y-6 rounded-2xl border border-[#e5d9cf] bg-white p-6 shadow-[0_14px_38px_rgba(73,48,32,.06)] sm:p-8"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#9a6038]">Store profile</p><div className="mt-5 grid gap-5 sm:grid-cols-2">{fields.map((field) => <label key={field.key} className="block text-sm font-semibold">{field.label}<input value={form[field.key]} onChange={(e) => update(field.key, e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3.5"/><span className="mt-2 block text-xs font-normal text-[#897e75]">{field.hint}</span></label>)}</div></div><div className="border-t border-[#eee6de] pt-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#9a6038]">Store operations</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="block text-sm font-semibold sm:col-span-2">Customer announcement<textarea value={form.announcement} onChange={(e) => update("announcement", e.target.value)} rows="3" className="mt-2 w-full rounded-xl border px-4 py-3.5"/><span className="mt-2 block text-xs font-normal text-[#897e75]">A short message for future storefront announcements.</span></label><label className="block text-sm font-semibold">Low stock threshold<input type="number" min="0" value={form.lowStockThreshold} onChange={(e) => update("lowStockThreshold", e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3.5"/><span className="mt-2 block text-xs font-normal text-[#897e75]">Products at or below this number are flagged.</span></label></div></div><div className="flex flex-col-reverse justify-end gap-3 border-t border-[#eee6de] pt-6 sm:flex-row"><button type="button" onClick={() => setForm(defaults)} className="rounded-xl border border-[#d9cbbf] px-5 py-3 text-sm font-semibold text-[#6f4933]">Reset</button><button disabled={saving} className="rounded-xl bg-[#9a6038] px-6 py-3 text-sm font-semibold text-white transition hover:bg-[#7d4829]">{saving ? "Saving..." : "Save changes"}</button></div></form>}</div></main>;
}
export default AdminSettings;
