import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

const categories = [
  { label: 'Living room', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=900&auto=format&fit=crop' },
  { label: 'Dining room', image: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?q=80&w=900&auto=format&fit=crop' },
  { label: 'Bedroom', image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?q=80&w=900&auto=format&fit=crop' },
];

const heroSlides = [
  { image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1500&auto=format&fit=crop', label: 'The quiet luxury edit', title: 'Natural textures. Everyday ease.', alt: 'Warm modern living room with a wooden coffee table and neutral seating' },
  { image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1500&auto=format&fit=crop', label: 'The considered home', title: 'Soft light. Strong character.', alt: 'Elegant neutral living room with curated furniture' },
  { image: 'https://images.unsplash.com/photo-1618220179428-22790b461013?q=80&w=1500&auto=format&fit=crop', label: 'The everyday edit', title: 'Designed to be lived in.', alt: 'Modern home interior with warm wood and natural textures' },
];

function Home() {
  const [activeSlide, setActiveSlide] = useState(0);
  useEffect(() => { document.title = 'FurniSelect | Thoughtful Furniture for Modern Living'; }, []);
  useEffect(() => {
    const timer = setInterval(() => setActiveSlide((current) => (current + 1) % heroSlides.length), 4500);
    return () => clearInterval(timer);
  }, []);
  const slide = heroSlides[activeSlide];
  return <main className="page-shell overflow-hidden bg-[#f8f6f2]">
    <section className="mx-auto grid max-w-[1380px] items-center gap-12 px-5 pb-16 pt-12 lg:grid-cols-[.88fr_1.12fr] lg:px-10 lg:pb-24 lg:pt-20">
      <div className="relative z-10 lg:pl-4"><p className="eyebrow">Furniture for the way you live</p><h1 className="serif mt-6 max-w-2xl text-[3.7rem] leading-[.98] tracking-[-.06em] text-[#26221f] sm:text-7xl lg:text-[6.4rem]">A softer place to <span className="text-[#9a6038]">land.</span></h1><p className="mt-7 max-w-lg text-base leading-8 text-[#716861] sm:text-lg">Thoughtful furniture, honest materials, and timeless shapes for homes with a point of view.</p><div className="mt-9 flex flex-wrap items-center gap-4"><Link to="/products" className="rounded-full bg-[#9a6038] px-7 py-4 text-sm font-semibold text-white shadow-[0_14px_28px_rgba(154,96,56,.22)] transition hover:-translate-y-0.5 hover:bg-[#7d4829]">Explore collection <span className="ml-2">-&gt;</span></Link><Link to="/ai-room" className="rounded-full border border-[#cdbdaf] bg-white/40 px-7 py-4 text-sm font-semibold text-[#5a3826] transition hover:bg-white">Find your style</Link></div><div className="mt-14 grid max-w-md grid-cols-3 border-t border-[#ded5cc] pt-5 text-xs text-[#81766e]"><span><strong className="block text-xl text-[#26221f]">500+</strong>curated designs</span><span><strong className="block text-xl text-[#26221f]">4.9/5</strong>customer rating</span><span><strong className="block text-xl text-[#26221f]">Made</strong>to last</span></div></div>
      <div className="relative lg:pl-10"><div className="absolute -right-16 -top-12 h-64 w-64 rounded-full bg-[#e3d3bf] blur-3xl"/><div className="relative overflow-hidden rounded-[2rem] bg-[#d1b395] p-2 shadow-[0_24px_80px_rgba(72,46,31,.16)]"><div className="relative h-[480px] overflow-hidden rounded-[1.55rem] sm:h-[630px] lg:h-[700px]"><img key={slide.image} src={slide.image} alt={slide.alt} className="h-full w-full object-cover transition-opacity duration-700"/><div className="absolute inset-0 bg-gradient-to-t from-black/45 via-transparent to-transparent"/><div className="absolute bottom-7 left-7 right-7 flex items-end justify-between text-white"><div><p className="text-[10px] uppercase tracking-[.2em] text-white/70">{slide.label}</p><p className="serif mt-2 text-2xl">{slide.title}</p></div><div className="flex items-center gap-2"><span className="rounded-full border border-white/30 bg-white/15 px-3 py-1.5 text-xs backdrop-blur">0{activeSlide + 1} / 0{heroSlides.length}</span></div></div></div></div><div className="relative mt-4 flex w-fit max-w-[calc(100%-1rem)] items-center gap-5 rounded-2xl border border-white bg-white/95 p-4 shadow-xl sm:ml-1"><div><p className="text-[10px] uppercase tracking-[.17em] text-[#9a6038]">New collection</p><p className="mt-1 text-sm font-semibold text-[#26221f]">Warm minimalism, made personal</p></div><div className="flex gap-1.5" aria-label="Hero image slides">{heroSlides.map((item, index) => <button key={item.image} onClick={() => setActiveSlide(index)} aria-label={`Show slide ${index + 1}`} className={`h-2 rounded-full p-0 transition-all ${index === activeSlide ? 'w-6 bg-[#9a6038]' : 'w-2 bg-[#d8c9bb]'}`}/>)}</div></div></div>
    </section>
    <section className="border-y border-[#e8e0d7] bg-white"><div className="mx-auto flex max-w-[1380px] flex-col justify-between gap-8 px-5 py-12 sm:flex-row sm:items-center lg:px-10"><div><p className="eyebrow">Designed around you</p><h2 className="serif mt-3 text-3xl tracking-[-.04em] sm:text-4xl">Good rooms begin with good choices.</h2></div><p className="max-w-md text-sm leading-7 text-[#716861]">From your first browse to the final delivery, we make it easier to create a home that feels considered, comfortable, and completely yours.</p></div></section>
    <section aria-labelledby="shop-by-room" className="mx-auto max-w-[1380px] px-5 py-20 lg:px-10 lg:py-28"><div className="flex items-end justify-between gap-6"><div><p className="eyebrow">Shop by room</p><h2 id="shop-by-room" className="serif mt-4 text-4xl tracking-[-.05em] sm:text-5xl">Set the mood.</h2></div><Link to="/products" className="hidden text-sm font-semibold text-[#9a6038] underline decoration-[#d5b69f] underline-offset-8 sm:block">View all furniture -&gt;</Link></div><div className="mt-10 grid gap-5 sm:grid-cols-3">{categories.map((category, index) => <Link to={`/products?search=${encodeURIComponent(category.label)}`} key={category.label} className="group relative overflow-hidden rounded-[1.5rem] bg-[#e5ddd4]"><img src={category.image} alt={`${category.label} furniture collection`} className="image-hover aspect-[.9] w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/55 via-transparent to-transparent"/><div className="absolute bottom-5 left-5 right-5 flex items-end justify-between text-white"><div><span className="text-[10px] uppercase tracking-[.18em] text-white/65">0{index + 1}</span><h3 className="serif mt-1 text-2xl">{category.label}</h3></div><span className="flex h-9 w-9 items-center justify-center rounded-full bg-white/20 opacity-0 backdrop-blur transition group-hover:opacity-100">-&gt;</span></div></Link>)}</div><Link to="/products" className="mt-8 inline-block text-sm font-semibold text-[#9a6038] underline decoration-[#d5b69f] underline-offset-8 sm:hidden">View all furniture -&gt;</Link></section>
    <section className="bg-[#e9e3da]"><div className="mx-auto grid max-w-[1380px] items-center gap-12 px-5 py-20 lg:grid-cols-[1fr_1fr] lg:px-10 lg:py-28"><div className="overflow-hidden rounded-[1.75rem]"><img src="https://images.unsplash.com/photo-1484101403633-562f891dc89a?q=80&w=1400&auto=format&fit=crop" alt="Curated modern home interior with warm wood accents" className="h-[420px] w-full object-cover sm:h-[580px]"/></div><div className="lg:pl-8"><p className="eyebrow">A smarter way to furnish</p><h2 className="serif mt-5 max-w-xl text-4xl leading-tight tracking-[-.05em] sm:text-6xl">Your room.<br/><span className="text-[#9a6038]">Your rhythm.</span></h2><p className="mt-6 max-w-md leading-8 text-[#716861]">Upload a photo of your space and let our AI Room Studio help you discover pieces that work with your light, layout, and personal style.</p><Link to="/ai-room" aria-label="Try AI Room Studio" className="mt-8 inline-flex min-h-14 items-center whitespace-nowrap rounded-full bg-[#26221f] px-6 py-3.5 text-sm font-semibold !text-white transition hover:bg-[#9a6038]"><span className="!text-white">Try AI Room Studio</span><span className="ml-3 !text-white">-&gt;</span></Link><div className="mt-10 grid max-w-md grid-cols-3 gap-3 border-t border-[#cfc2b4] pt-5 text-xs text-[#81766e]"><span><strong className="mb-1 block text-[#26221f]">01</strong>Upload</span><span><strong className="mb-1 block text-[#26221f]">02</strong>Discover</span><span><strong className="mb-1 block text-[#26221f]">03</strong>Make it yours</span></div></div></div></section>
    <section className="mx-auto max-w-[1380px] px-5 py-20 text-center lg:px-10 lg:py-28"><p className="eyebrow">Bring home your next favourite</p><h2 className="serif mx-auto mt-5 max-w-3xl text-4xl leading-tight tracking-[-.05em] sm:text-6xl">The pieces that make a house feel like home.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-[#716861]">Explore furniture designed to be lived with, loved for longer, and remembered.</p><Link to="/products" className="mt-8 inline-block rounded-full bg-[#9a6038] px-7 py-4 text-sm font-semibold text-white transition hover:bg-[#7d4829]">Shop the collection -&gt;</Link></section>
  </main>;
}

export default Home;
