import { useEffect, useState } from 'react';
import axios from 'axios';
import { Link, useLocation, useNavigate } from 'react-router-dom';

function Products() {
  const [products, setProducts] = useState([]); const [loading, setLoading] = useState(true); const [sort, setSort] = useState('featured');
  const location = useLocation(); const navigate = useNavigate();
  useEffect(() => { (async () => { try { setLoading(true); const search = new URLSearchParams(location.search).get('search') || ''; const { data } = await axios.get(`https://furniselect-ai.onrender.com/api/products?search=${search}`); setProducts(data); } catch { setProducts([]); } finally { setLoading(false); } })(); }, [location.search]);
  const displayed = [...products].sort((a, b) => sort === 'low' ? a.price - b.price : sort === 'high' ? b.price - a.price : 0);
  return <main className="page-shell bg-[#f7f3ee]"><div className="mx-auto max-w-[1320px] px-5 py-12 lg:px-8 lg:py-20"><div className="flex flex-col justify-between gap-8 border-b border-[#e0d6cd] pb-10 md:flex-row md:items-end"><div><p className="eyebrow">The collection</p><h1 className="serif mt-4 text-5xl tracking-[-.04em] sm:text-6xl">Pieces with presence.</h1><p className="mt-4 max-w-lg leading-7 text-[#756b63]">Considered furniture for rooms that feel collected, not crowded.</p></div><div className="flex items-center gap-3"><span className="text-sm text-[#897e75]">{products.length} pieces</span><select value={sort} onChange={e => setSort(e.target.value)} className="rounded-full border border-[#d8c8bb] bg-transparent px-4 py-2 text-sm outline-none"><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div></div>{loading ? <div className="grid gap-6 py-12 sm:grid-cols-2 lg:grid-cols-3"><div className="h-96 animate-pulse rounded-3xl bg-[#e9e0d7]"/><div className="h-96 animate-pulse rounded-3xl bg-[#e9e0d7]"/><div className="h-96 animate-pulse rounded-3xl bg-[#e9e0d7]"/></div> : displayed.length === 0 ? <div className="py-28 text-center"><p className="text-4xl">⌂</p><h2 className="serif mt-4 text-3xl">Nothing here yet</h2><p className="mt-2 text-[#756b63]">Try a different search or browse the full collection.</p><button onClick={() => navigate('/products')} className="mt-6 rounded-full bg-[#5c3927] px-5 py-3 text-sm font-semibold text-white">View all pieces</button></div> : <div className="grid gap-x-6 gap-y-12 pt-12 sm:grid-cols-2 lg:grid-cols-3">{displayed.map(product => <Link key={product._id} to={`/products/${product._id}`} className="group"><div className="relative overflow-hidden rounded-[1.6rem] bg-[#eee5dc]"><img src={product.image} alt={product.title} className="image-hover aspect-[4/5] w-full object-cover"/><span className="absolute left-4 top-4 rounded-full bg-white/85 px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider text-[#5c3927] backdrop-blur">{product.category}</span><span className="absolute bottom-4 right-4 flex h-10 w-10 translate-y-2 items-center justify-center rounded-full bg-white text-lg text-[#5c3927] opacity-0 shadow-lg transition group-hover:translate-y-0 group-hover:opacity-100">↗</span></div><div className="flex items-start justify-between gap-4 pt-5"><div><h2 className="font-semibold tracking-[-.02em]">{product.title}</h2><p className="mt-1 text-sm text-[#897e75]">{product.category}</p></div><p className="font-semibold text-[#8a5a3c]">₹{Number(product.price).toLocaleString('en-IN')}</p></div></Link>)}</div>}</div></main>;
}
export default Products;
